# Generated by Django 5.2.8 on 2025-11-18 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={"ordering": ("license_number",)},
        ),
        migrations.RenameField(
            model_name="driver",
            old_name="license_numer",
            new_name="license_number",
        ),
    ]
